name: Cass Operator Build & Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_operator_docker:
    name: Build Cass Operator Docker Image
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.13
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install Mage
        run: |
          cd /tmp
          wget https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz
          tar -xvf mage_1.9.0_Linux-64bit.tar.gz
          mkdir -p $GOPATH/bin
          mv mage $GOPATH/bin/mage
          sudo chmod +x $GOPATH/bin/mage
      - name: Test Sdk Generate
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          mage operator:testSdkGenerate
      - name: Test Client Generate
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          mage operator:testGenerateClient
      - name: Build docker - standard and ubi images
        env:
          PR_REF: ${{ github.event.pull_request.head.ref }}
          MO_BASE_OS: 'registry.c3.ai/ubi7/ubi-minimal:7.8.366.1'
          MO_ART_USR: ${{ secrets.ART_USR }}
          MO_ART_PSW: ${{ secrets.ART_PSW }}
          MO_ART_REPO: 'registry.c3.ai'
        run: |
          if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
            export MO_BRANCH=${PR_REF}
          else
            export MO_BRANCH="master"
          fi;
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          mage operator:artifactoryDockerLogin
          mage operator:testAndBuild
      - name: Deploy to Artifactory
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'c3-amitsalunke/cass-operator'
        env:
          MO_ART_USR: ${{ secrets.ART_USR }}
          MO_ART_PSW: ${{ secrets.ART_PSW }}
          MO_ART_REPO: 'ci-registry.c3iot.io'
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          export MO_TAGS=$(cat ./build/tagsToPush.txt)
          mage operator:deployToArtifactory
      # - name: Deploy to GH Packages
      #   if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'datastax/cass-operator'
      #   env:
      #     MO_GH_USR: 'datastax/cass-operator'
      #     MO_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     MO_GH_PKG_REPO: 'datastax/cass-operator/operator'
      #   run: |
      #     export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      #     export MO_TAGS=$(cat ./build/tagsToPush.txt)
      #     mage operator:deployToGHPackages
